/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.umg.vistas;

import com.digitalpersona.uareu.*;
import com.umg.biometric.CaptureThread;
import com.umg.message.MessageBox;
import com.umg.sql.FingerprintDAO;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.time.LocalDate;
import java.time.temporal.ChronoUnit;
import javax.swing.*;

import com.umg.modelos.EmpleadoAsistencia;


/**
 *
 * @author sebas
 */
public class VerificarHuella extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form VerificarHuella
     */
    private CaptureThread m_capture;
    private Reader m_reader;
    private static final String ACT_BACK = "back";
    private javax.swing.Timer resetTimer;
    public static LocalDate fechaHoy = LocalDate.now();
    public static String titulos[] = {"DPI Empleado",
            "Nombre Completo",
            "Hora de registro",
            "Hora de salida",
            "Mensaje"};

    public VerificarHuella() {
        initComponents();    // Primero inicializamos componentes

        setTitle("Toma de Asistencia ASSENTA"); // Opcional
        setLocationRelativeTo(null);             // Centrado, aunque ya es pantalla completa
        setResizable(false);                     // Opcional
        inicializarComponentes();
        m_reader = obtenerReader();
        addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent e) {
                cerrarAplicacion();
            }
        });
        if (m_reader != null) {
            try {
                m_reader.Open(Reader.Priority.COOPERATIVE);
                StartCaptureThread();
            } catch (UareUException e) {
                MessageBox.DpError("Error al abrir lector", e);
            }
        } else {
            JOptionPane.showMessageDialog(this, "No se encontró lector.");
            System.exit(0);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtExitoFallo = new javax.swing.JLabel();
        titulo5 = new javax.swing.JLabel();
        txtNombreCom = new javax.swing.JLabel();
        titulo2 = new javax.swing.JLabel();
        titulo3 = new javax.swing.JLabel();
        titulo4 = new javax.swing.JLabel();
        lblFechaHoy = new javax.swing.JLabel();
        txtMensaje = new javax.swing.JLabel();
        txtDpiEmpleado = new javax.swing.JLabel();
        txtHoraRegistro = new javax.swing.JLabel();
        txtHoraSalida = new javax.swing.JLabel();
        titulo1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Toma de Asistencia ASSENTA");
        setExtendedState(MAXIMIZED_BOTH);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtExitoFallo.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        txtExitoFallo.setForeground(new java.awt.Color(102, 102, 0));
        txtExitoFallo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtExitoFallo.setText("Esperando huella...");
        jPanel2.add(txtExitoFallo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 1180, -1));

        titulo5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titulo5.setForeground(new java.awt.Color(102, 102, 0));
        titulo5.setText("Mensaje");
        jPanel2.add(titulo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, -1, -1));

        txtNombreCom.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombreCom.setForeground(new java.awt.Color(102, 102, 0));
        txtNombreCom.setText(" ");
        jPanel2.add(txtNombreCom, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 160, 970, -1));

        titulo2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titulo2.setForeground(new java.awt.Color(102, 102, 0));
        titulo2.setText("Nombre Completo");
        jPanel2.add(titulo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, -1));

        titulo3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titulo3.setForeground(new java.awt.Color(102, 102, 0));
        titulo3.setText("Hora de registro");
        jPanel2.add(titulo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        titulo4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titulo4.setForeground(new java.awt.Color(102, 102, 0));
        titulo4.setText("Hora de salida");
        jPanel2.add(titulo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, -1));

        lblFechaHoy.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblFechaHoy.setForeground(new java.awt.Color(102, 102, 0));
        lblFechaHoy.setText("DPI Empleado");
        jPanel2.add(lblFechaHoy, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 130, -1, -1));

        txtMensaje.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMensaje.setForeground(new java.awt.Color(102, 102, 0));
        txtMensaje.setText(" ");
        txtMensaje.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jPanel2.add(txtMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 310, 1060, 140));

        txtDpiEmpleado.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDpiEmpleado.setForeground(new java.awt.Color(102, 102, 0));
        txtDpiEmpleado.setText(" ");
        jPanel2.add(txtDpiEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 610, -1));

        txtHoraRegistro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHoraRegistro.setForeground(new java.awt.Color(102, 102, 0));
        txtHoraRegistro.setText(" ");
        jPanel2.add(txtHoraRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 200, 990, -1));

        txtHoraSalida.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtHoraSalida.setForeground(new java.awt.Color(102, 102, 0));
        txtHoraSalida.setText(" ");
        jPanel2.add(txtHoraSalida, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 240, 990, -1));

        titulo1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        titulo1.setForeground(new java.awt.Color(102, 102, 0));
        titulo1.setText("DPI Empleado");
        jPanel2.add(titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1220, 500));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Registro de asistencia");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1220, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1220, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerificarHuella.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerificarHuella.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerificarHuella.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerificarHuella.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerificarHuella().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JLabel lblFechaHoy;
    public javax.swing.JLabel titulo1;
    public javax.swing.JLabel titulo2;
    public javax.swing.JLabel titulo3;
    public javax.swing.JLabel titulo4;
    public javax.swing.JLabel titulo5;
    public javax.swing.JLabel txtDpiEmpleado;
    public javax.swing.JLabel txtExitoFallo;
    public javax.swing.JLabel txtHoraRegistro;
    public javax.swing.JLabel txtHoraSalida;
    public javax.swing.JLabel txtMensaje;
    public javax.swing.JLabel txtNombreCom;
    // End of variables declaration//GEN-END:variables
    public Reader obtenerReader() {
        Reader reader = null;
        try {
            ReaderCollection readers = UareUGlobal.GetReaderCollection();
            readers.GetReaders(); // Refrescar la lista de dispositivos conectados

            if (readers.size() == 0) {
                System.out.println("❌ No se detectaron lectores de huella.");
                return null;
            }

            reader = readers.get(0); // Selecciona automáticamente el primer lector encontrado
            System.out.println("✅ Lector seleccionado automáticamente: " + reader.GetDescription().name);

        } catch (UareUException e) {
            System.err.println("❌ Error inicializando el lector: " + e.getMessage());
        }

        return reader;
    }

    @Override
    public void actionPerformed(ActionEvent e) {
        if (e.getActionCommand().equals(ACT_BACK)) {
            StopCaptureThread();
        } else if (e.getActionCommand().equals(CaptureThread.ACT_CAPTURE)) {
            CaptureThread.CaptureEvent evt = (CaptureThread.CaptureEvent) e;
            if (ProcessCaptureResult(evt)) {
                WaitForCaptureThread();
                StartCaptureThread();
            } else {
            }
        }
    }

    private void StartCaptureThread() {
        m_capture = new CaptureThread(m_reader, false, Fid.Format.ANSI_381_2004, Reader.ImageProcessing.IMG_PROC_DEFAULT);
        m_capture.start(this);
    }

    private void StopCaptureThread() {
        if (m_capture != null) {
            m_capture.cancel();
        }
    }   

    private void WaitForCaptureThread() {
        if (m_capture != null) {
            m_capture.join(1000);
        }
    }

    private boolean ProcessCaptureResult(CaptureThread.CaptureEvent evt) {
        boolean bCanceled = false;

        if (evt.capture_result != null) {
            if (evt.capture_result.image != null && Reader.CaptureQuality.GOOD == evt.capture_result.quality) {
                Engine engine = UareUGlobal.GetEngine();

                try {
                    Fmd probe = engine.CreateFmd(evt.capture_result.image, Fmd.Format.ANSI_378_2004);

                    // Buscar huella en base de datos
                    EmpleadoAsistencia empleadoRegistrado = new FingerprintDAO().validateFingerprint(probe);
                    if (empleadoRegistrado != null) {
                        boolean registrado = new FingerprintDAO().registrarAsistencia(empleadoRegistrado.getId(),
                                String.valueOf(LocalDate.now()),
                                java.time.LocalTime.now().truncatedTo(ChronoUnit.SECONDS).toString());

                        if (registrado) {
                            mostrarComponentes();
                            txtExitoFallo.setText("Huella reconocida");
                            txtMensaje.setText("Asistencia guardada correctamente\nNo olvides registrarte al salir");
                            txtDpiEmpleado.setText(empleadoRegistrado.getDpi()); // Simulado, aquí pones el real si lo buscas
                            txtNombreCom.setText(empleadoRegistrado.getNombreCompleto()); // Igual
                            txtHoraRegistro.setText(java.time.LocalTime.now().truncatedTo(ChronoUnit.SECONDS).toString());
                            txtHoraSalida.setText(empleadoRegistrado.getHoraSalida()); // Vacío o calculado
                            jPanel2.setBackground(new java.awt.Color(204, 255, 204));
                        } else {
                            titulo5.setText(titulos[4]);
                            txtExitoFallo.setText("Salida ya registrada");
                            txtMensaje.setText("El sistema ya no puede procesar su asistencia, salida ya marcada");
                            jPanel2.setBackground(new java.awt.Color(255, 204, 204));
                            ocultarComponentes();
                            limpiarCampos();
                        }
                    } else {
                        titulo5.setText(titulos[4]);
                        txtExitoFallo.setText("Huella no reconocida");
                        txtMensaje.setText("No se encontró coincidencia. Regístrese o consulte al encargado.");
                        jPanel2.setBackground(new java.awt.Color(255, 204, 204));
                        ocultarComponentes();
                        limpiarCampos();
                    }

                    iniciarTimerReset();

                } catch (UareUException e) {
                    MessageBox.DpError("Engine.CreateFmd()", e);
                }

            } else if (Reader.CaptureQuality.CANCELED == evt.capture_result.quality) {
                bCanceled = true;
            } else {
                MessageBox.BadQuality(evt.capture_result.quality);
            }
        } else if (evt.exception != null) {
            MessageBox.DpError("Capture", evt.exception);
            bCanceled = true;
        } else if (evt.reader_status != null) {
            MessageBox.BadStatus(evt.reader_status);
            bCanceled = true;
        }

        return !bCanceled;
    }

    private void limpiarCampos() {
        txtDpiEmpleado.setText("");
        txtNombreCom.setText("");
        txtHoraRegistro.setText("");
        txtHoraSalida.setText("");
    }


    private void inicializarComponentes() {
        titulo1.setText(" ");
        titulo2.setText(" ");
        titulo3.setText(" ");
        titulo4.setText(" ");
        titulo5.setText(" ");
        txtMensaje.setText(" ");
        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        txtExitoFallo.setText("Esperando huella...");
        lblFechaHoy.setText(String.valueOf("Fecha de hoy: "+fechaHoy));
    }

    private void mostrarComponentes() {
        titulo1.setText(titulos[0]);
        titulo2.setText(titulos[1]);
        titulo3.setText(titulos[2]);
        titulo4.setText(titulos[3]);
        titulo5.setText(titulos[4]);
    }

    private void ocultarComponentes() {
        titulo1.setText("");
        titulo2.setText("");
        titulo3.setText("");
        titulo4.setText("");
    }

    private void iniciarTimerReset() {
        if (resetTimer != null && resetTimer.isRunning()) {
            resetTimer.stop();
        }

        resetTimer = new javax.swing.Timer(3000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                limpiarCampos();
                inicializarComponentes();
                resetTimer.stop();
            }
        });
        resetTimer.setRepeats(false);
        resetTimer.start();
    }

    private void cerrarAplicacion() {
        StopCaptureThread(); // Cancela captura primero si es necesario
        try {
            UareUGlobal.DestroyReaderCollection();
            System.out.println("Colección de lectores destruida correctamente.");
        } catch (UareUException e) {
            MessageBox.DpError("UareUGlobal.DestroyReaderCollection()", e);
        }
        System.exit(0); // Finalmente, cierra la aplicación
    }


}